SKILL_APPLICATION_FAILURE_PENALTY = -1
SKILL_APPLICATION_SUCCESS_REWARD = 1

BALL_INSERT_SUCCESS_REWARD = 1  # 插入球成功的奖励
DEFENCE_REWARD = 1  # 防御奖励
RETURN_REWARD = 2   # 反弹奖励
PRETA_REWARD = 2    # 饿鬼奖励

BYAKUGAN_SUCCESS_REWARD = 1
DEATH_CONTROLLING_POSSESSED_BLOOD_REWARD = 2
SHADOW_CLONE_REWARD = 2
SHARINGAN_REWARD = 3
SIX_PATHS_MODE_REWARD = 5

BALL_APPLICATION_FAILURE_PENALTY = -1
BIND_SUCCESS_REWARD = 1
EXPOSE_SUCCESS_REWARD = 2
SEAL_ACUPOINT_SUCCESS_REWARD = 1